[package]
name = "osmium-nn"
version = "0.1.0"
authors = ["Ethan Jaszewski <ethanjaszewski@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2"
rand = "0.8.0"
